name: Build Chelly Official APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Code Download
        uses: actions/checkout@v4

      - name: 2. Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: 3. Make Gradlew Work
        run: chmod +x gradlew

      - name: 4. Build Master APK
        # यहाँ हमने 'cd android' हटा दिया है, क्योंकि gradlew रूट में है
        run: ./gradlew assembleDebug --stacktrace

      - name: 5. Final Download Link
        uses: actions/upload-artifact@v4
        with:
          name: Chelly-Final-App
          # Chelly में APK आमतौर पर यहाँ बनती है:
          path: app/build/outputs/apk/debug/*.apk
